# Outroduction {.unnumbered}

Lessons learned from each experiment can be fed into an ongoing cycle of improvement. Systematically asking the kinds of questions outlined in the preceding section (Were there unexpected noise patterns? Recruitment challenges? Higher-than-expected failures on comprehension/attention checks?) helps to ensure that every experiment strengthens the design, quality, and efficiency of those that follow.

We have outlined ten principles to optimize the design and delivery of crowdsourced behavioral experiments, enabling researchers to avoid pitfalls and harness the advantages of this approach. Applied in concert, they transform crowdsourcing from a simple convenience into a powerful engine for advancing behavioral science.

If you have found this resource helpful for designing and implementing your online experiment, please consider citing it in your research:

`Warburton, M., Tsay, J.S. How to conduct behavioural experiments online. Nature Human Behaviour (2026). https://doi.org/10.1038/s41562-026-02465-w`